import type { Metadata } from 'next'
import Link from 'next/link'
import { BreadcrumbSchema } from '@/components/BlogPostSchema'

export const metadata: Metadata = {
  title: 'Brand Kit Examples — See What BrandForge Creates | BrandForge',
  description: 'Explore real brand kit examples generated by BrandForge — complete with logo concepts, color palettes, taglines, typography, and domain suggestions. See what your brand could look like.',
  keywords: [
    'brand kit examples',
    'brand identity examples',
    'logo concepts',
    'brand color palette examples',
    'brand guidelines examples',
    'brand kit template',
    'brand identity template',
  ],
  openGraph: {
    title: 'Brand Kit Examples — See What BrandForge Creates',
    description: 'Explore real brand kit examples with logos, color palettes, taglines, and more. See what your brand could look like.',
    url: 'https://brandforge-phi-pearl.vercel.app/examples',
    siteName: 'BrandForge',
    type: 'website',
    images: [
      {
        url: '/opengraph-image',
        width: 1200,
        height: 630,
        alt: 'BrandForge Brand Kit Examples',
      },
    ],
  },
}

const brandExamples = [
  {
    name: 'Ember & Oak',
    industry: 'Restaurant & Bar',
    description: 'A farm-to-fire restaurant in Portland specializing in wood-fired cuisine and craft cocktails.',
    tagline: 'Where fire meets flavor.',
    colors: ['#2D1B0E', '#C75B39', '#E8D5B7', '#4A7C59', '#1A1A2E'],
    colorNames: ['Charcoal Bark', 'Ember Orange', 'Cream Linen', 'Forest Sage', 'Midnight'],
    font: 'Playfair Display + Inter',
    logoDescription: 'A minimal campfire icon formed from two intersecting lines — one straight (oak), one curved (ember). Clean, warm, and versatile across signage and menus.',
    domain: 'emberandoak.com',
    socialHint: '@emberandoak available on Twitter, Instagram',
    vibe: 'Rustic warm',
  },
  {
    name: 'Nimbly',
    industry: 'SaaS / Tech Startup',
    description: 'An AI workflow automation platform that helps teams move faster with fewer bottlenecks.',
    tagline: 'Work at the speed of thought.',
    colors: ['#3B6FF5', '#7C3AED', '#0F172A', '#F8FAFC', '#10B981'],
    colorNames: ['Brand Blue', 'Purple Accent', 'Slate Dark', 'Cloud White', 'Action Green'],
    font: 'Inter + JetBrains Mono',
    logoDescription: 'A stylized "N" formed from three angled lines suggesting forward momentum and flow. Works as a standalone icon for app badges and favicons.',
    domain: 'nimbly.io',
    socialHint: '@nimblyapp available on Twitter, Instagram',
    vibe: 'Fast, clean',
  },
  {
    name: 'Salt & Stone',
    industry: 'Skincare & Wellness',
    description: 'A mineral-based skincare line using sea salt and volcanic stone extracts for deep skin renewal.',
    tagline: 'Elements your skin remembers.',
    colors: ['#8B9DAF', '#D4C5B2', '#2C3E50', '#FAF8F5', '#B8A99A'],
    colorNames: ['Ocean Fog', 'Sand Shell', 'Deep Slate', 'Alabaster', 'Warm Pebble'],
    font: 'Cormorant Garamond + Avenir',
    logoDescription: 'Two overlapping circles — one representing salt (crystalline edges), one representing stone (solid, smooth). Earthy elegance without being fussy.',
    domain: 'saltandstone.co',
    socialHint: '@saltandstone available on Instagram, TikTok',
    vibe: 'Minimal luxury',
  },
  {
    name: 'PulseFit',
    industry: 'Fitness & Health',
    description: 'A heart-rate-based fitness platform that personalizes workouts to your body\'s real-time signals.',
    tagline: 'Train to your own rhythm.',
    colors: ['#EF4444', '#0F172A', '#22D3EE', '#F8FAFC', '#6366F1'],
    colorNames: ['Pulse Red', 'Slate Black', 'Energy Cyan', 'Cloud White', 'Recovery Indigo'],
    font: 'Montserrat + Roboto Mono',
    logoDescription: 'A heartbeat line that transforms into a flexing arm at its peak. Dynamic, bold, and instantly recognizable at small sizes.',
    domain: 'pulsefit.com',
    socialHint: '@pulsefit available on Twitter, Instagram, TikTok',
    vibe: 'High energy',
  },
  {
    name: 'Meridian Group',
    industry: 'Consulting & Advisory',
    description: 'A strategic advisory firm helping mid-market companies navigate growth and transformation.',
    tagline: 'Navigate what\'s next.',
    colors: ['#1E3A5F', '#C9A84C', '#F5F1E8', '#374151', '#FFFFFF'],
    colorNames: ['Navy Steel', 'Gold Meridian', 'Parchment', 'Slate Grey', 'White'],
    font: 'Georgia + Trade Gothic',
    logoDescription: 'A compass rose simplified to four directional lines with a gold circle at its center. Sophisticated and authoritative — works beautifully on letterhead and proposals.',
    domain: 'meridiangroup.com',
    socialHint: '@meridiangroup available on LinkedIn',
    vibe: 'Authoritative',
  },
  {
    name: 'StoryForge',
    industry: 'Creative Agency',
    description: 'A brand storytelling agency that helps startups craft narratives that convert audiences into communities.',
    tagline: 'Build brands worth telling.',
    colors: ['#7C3AED', '#F59E0B', '#0F172A', '#FAFAFA', '#EC4899'],
    colorNames: ['Violet Ink', 'Amber Spark', 'Dark Narrative', 'White Page', 'Pink Accent'],
    font: 'Outfit + Source Serif Pro',
    logoDescription: 'An open book that doubles as a blacksmith\'s anvil — stories being forged. Playful enough for creative work, strong enough for business cards.',
    domain: 'storyforge.co',
    socialHint: '@storyforge available on Twitter, Instagram, Dribbble',
    vibe: 'Creative bold',
  },
]

export default function ExamplesPage() {
  return (
    <>
      <BreadcrumbSchema items={[{ name: 'Examples', href: '/examples' }]} />
      {/* Examples page WebPage Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'WebPage',
            name: 'Brand Kit Examples — See What BrandForge Creates',
            description: 'Explore real brand kit examples generated by BrandForge — complete with logo concepts, color palettes, taglines, typography, and domain suggestions.',
            url: 'https://brandforge-phi-pearl.vercel.app/examples',
            publisher: {
              '@type': 'Organization',
              name: 'BrandForge',
              url: 'https://brandforge-phi-pearl.vercel.app',
            },
          }),
        }}
      />
      <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <p className="text-sm font-semibold text-brand-600 mb-3 tracking-wider uppercase">
            Brand Kit Examples
          </p>
          <h1 className="text-4xl font-bold tracking-tight text-slate-900 sm:text-5xl">
            See what your brand could look like
          </h1>
          <p className="mt-4 text-lg text-slate-500 max-w-2xl mx-auto">
            Every BrandForge name comes with a complete brand kit — logo concept, color palette, 
            tagline, typography, domain and social checks. Here are real examples.
          </p>
        </div>

        {/* Examples Grid */}
        <div className="space-y-12">
          {brandExamples.map((brand) => (
            <div key={brand.name} className="rounded-3xl border border-slate-200 bg-white overflow-hidden shadow-sm">
              {/* Header bar with colors */}
              <div className="flex h-3">
                {brand.colors.map((color) => (
                  <div key={color} className="flex-1" style={{ backgroundColor: color }} />
                ))}
              </div>
              
              <div className="p-6 sm:p-8 lg:p-10">
                <div className="grid gap-8 lg:grid-cols-2">
                  {/* Left: Brand info */}
                  <div>
                    <div className="flex items-center gap-3 mb-1">
                      <h2 className="text-2xl font-bold text-slate-900">{brand.name}</h2>
                      <span className="text-xs text-slate-400 bg-slate-100 px-2 py-0.5 rounded-full">{brand.vibe}</span>
                    </div>
                    <p className="text-sm text-brand-600 font-medium mb-4">{brand.industry}</p>
                    
                    <p className="text-slate-700 text-sm leading-relaxed mb-4">{brand.description}</p>
                    
                    {/* Tagline */}
                    <div className="rounded-lg bg-slate-50 px-4 py-3 mb-6">
                      <p className="text-xs text-slate-400 font-medium uppercase tracking-wide mb-1">Tagline</p>
                      <p className="text-slate-900 font-semibold italic">&ldquo;{brand.tagline}&rdquo;</p>
                    </div>

                    {/* Logo description */}
                    <div className="mb-6">
                      <p className="text-xs text-slate-400 font-medium uppercase tracking-wide mb-2">Logo Concept</p>
                      <p className="text-sm text-slate-700 leading-relaxed">{brand.logoDescription}</p>
                    </div>

                    {/* Typography */}
                    <div className="mb-6">
                      <p className="text-xs text-slate-400 font-medium uppercase tracking-wide mb-2">Typography</p>
                      <p className="text-sm text-slate-700">{brand.font}</p>
                    </div>
                  </div>

                  {/* Right: Color palette & availability */}
                  <div>
                    {/* Color Palette */}
                    <div className="mb-8">
                      <p className="text-xs text-slate-400 font-medium uppercase tracking-wide mb-3">Color Palette</p>
                      <div className="grid grid-cols-5 gap-2">
                        {brand.colors.map((color, i) => (
                          <div key={color}>
                            <div 
                              className="h-16 rounded-lg shadow-inner border border-slate-100" 
                              style={{ backgroundColor: color }}
                            />
                            <p className="text-xs text-slate-500 mt-1 text-center truncate">{brand.colorNames[i]}</p>
                            <p className="text-xs text-slate-400 text-center font-mono">{color}</p>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Domain & Social */}
                    <div>
                      <p className="text-xs text-slate-400 font-medium uppercase tracking-wide mb-3">Availability</p>
                      <div className="space-y-2">
                        <div className="flex items-center gap-2 text-sm">
                          <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                          </svg>
                          <span className="text-slate-700">{brand.domain}</span>
                          <span className="text-xs text-green-600 font-medium">Available</span>
                        </div>
                        <div className="flex items-center gap-2 text-sm">
                          <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                          </svg>
                          <span className="text-slate-700">{brand.socialHint}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* CTA Section */}
        <div className="mt-16 text-center">
          <div className="rounded-3xl bg-gradient-to-br from-brand-50 via-white to-purple-50 p-8 sm:p-12">
            <h2 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
              Ready to create <span className="gradient-text">your</span> brand kit?
            </h2>
            <p className="mt-4 text-lg text-slate-600 max-w-xl mx-auto">
              Describe your business and get a complete brand kit with logo concepts, colors, taglines, 
              and availability checks — in under a minute.
            </p>
            <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
              <a href="/generate" className="btn-primary text-base px-8 py-3">
                Generate My Brand — Free
              </a>
              <a href="/brand-kit" className="btn-secondary text-base px-8 py-3">
                View Brand Kit Features
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}