'use client'

import { useState, useCallback, useEffect, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import type { GeneratedName, BusinessName, AvailabilityStatus } from '@/types'
import { isFavorite, toggleFavorite } from '@/lib/favorites'
import NameResultsGrid from '@/components/NameResultsGrid'

const INDUSTRIES = [
  'Technology', 'Food & Beverage', 'Fashion', 'Health & Wellness',
  'Finance', 'Education', 'Entertainment', 'E-commerce', 'Real Estate', 'Other'
]

const EXAMPLE_PROMPTS = [
  {
    label: 'Coffee Shop',
    emoji: '☕',
    text: 'A sustainable coffee shop in Brooklyn that sources fair-trade beans and hosts community events',
  },
  {
    label: 'SaaS Tool',
    emoji: '⚡',
    text: 'A project management tool for remote teams that uses AI to prioritize tasks automatically',
  },
  {
    label: 'Fitness App',
    emoji: '💪',
    text: 'A personal fitness app that creates workouts based on your mood and available equipment',
  },
  {
    label: 'Fashion Brand',
    emoji: '👗',
    text: 'A minimalist sustainable fashion brand making timeless wardrobe essentials from recycled fabrics',
  },
  {
    label: 'Marketing Agency',
    emoji: '📈',
    text: 'A digital marketing agency specializing in helping small businesses grow through social media',
  },
  {
    label: 'Food Delivery',
    emoji: '🍕',
    text: 'A farm-to-door meal delivery service connecting local farms with busy families',
  },
]

const GENERATE_FAQ = [
  {
    question: 'Is the business name generator really free?',
    answer: 'Yes! You get 5 free name generations, each returning 5 unique business name suggestions. That\'s 25 free name ideas with no credit card required. If you want full brand kits with logo concepts, color palettes, and taglines, you can upgrade to Pro for $9 per brand kit.',
  },
  {
    question: 'How does the AI generate business names?',
    answer: 'BrandForge uses advanced AI to analyze your business description — your industry, target audience, values, and vibe. It generates names that are unique, memorable, and tailored specifically to your vision. Each name comes with a meaning, a style category, and a suggested domain.',
  },
  {
    question: 'What makes a good business name?',
    answer: 'A great business name is memorable, easy to spell and pronounce, reflects your brand\'s personality, and is available as a .com domain and on social platforms. Our AI prioritizes these qualities — every name suggestion is checked for domain and social handle availability in real time.',
  },
  {
    question: 'Can I check if a name is already taken?',
    answer: 'Absolutely. BrandForge automatically checks .com domain availability and social media handle availability (Twitter/X and Instagram) for every name it suggests. Green means available, red means taken — no guesswork.',
  },
  {
    question: 'What\'s included in a brand kit?',
    answer: 'Each brand kit includes a unique business name with meaning, an AI-generated logo concept, a 5-color brand palette with hex codes, a memorable tagline, typography recommendations, domain availability check, and social media handle availability. Pro members can also export the full kit as a PDF.',
  },
  {
    question: 'How is this different from a random name generator?',
    answer: 'Random name generators just mash words together. BrandForge uses AI to understand your business concept and generate names that actually fit — names with meaning, style, and intentionality behind them. It also gives you a complete brand identity, not just a name on its own.',
  },
  {
    question: 'Can I use the generated names for my business?',
    answer: 'Yes! The names generated by BrandForge are yours to use. We recommend checking trademark availability in your jurisdiction before committing, but the names themselves are original and generated specifically for you.',
  },
]

/** Convert API response (GeneratedName[]) to UI-ready BusinessName[] */
function toBusinessNames(raw: GeneratedName[], industry: string): BusinessName[] {
  return raw.map((n) => ({
    ...n,
    id: crypto.randomUUID(),
    industry: industry || 'General',
    domainAvailable: 'unknown' as const,
    twitterAvailable: 'unknown' as const,
    instagramAvailable: 'unknown' as const,
    isFavorite: isFavorite(n.name),
    domainSuggestion: n.domainSuggestion || `${n.name.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`,
  }))
}

function GeneratePageContent() {
  const searchParams = useSearchParams()
  const initialDesc = searchParams.get('desc') || ''

  const [description, setDescription] = useState(initialDesc)
  const [industry, setIndustry] = useState('')
  const [names, setNames] = useState<BusinessName[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [hasGenerated, setHasGenerated] = useState(false)

  async function handleGenerate(e?: React.FormEvent) {
    if (e) e.preventDefault()
    if (!description.trim()) return

    setLoading(true)
    setError('')
    setNames([])
    setHasGenerated(true)

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ description: description.trim(), industry: industry || undefined }),
      })

      if (!res.ok) {
        const data = await res.json()
        throw new Error(data.error || 'Generation failed')
      }

      const data = await res.json()
      const businessNames = toBusinessNames(data.names, industry)
      setNames(businessNames)
    } catch (err: any) {
      setError(err.message || 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }

  const handleToggleFavorite = useCallback((id: string) => {
    setNames((prev) =>
      prev.map((n) => {
        if (n.id !== id) return n
        const newFav = toggleFavorite(n.name, n.meaning, n.style, n.industry)
        return { ...n, isFavorite: newFav }
      })
    )
  }, [])

  // Check domain availability for each name after generation
  const checkDomainAvailability = useCallback(async (nameId: string, domain: string) => {
    // Mark as "checking"
    setNames((prev) =>
      prev.map((n) =>
        n.id === nameId ? { ...n, domainAvailable: 'checking' as AvailabilityStatus } : n
      )
    )

    try {
      const res = await fetch(`/api/check-domain?domain=${encodeURIComponent(domain)}`)
      const data = await res.json()
      setNames((prev) =>
        prev.map((n) =>
          n.id === nameId ? { ...n, domainAvailable: data.available ? 'available' as AvailabilityStatus : 'taken' as AvailabilityStatus } : n
        )
      )
    } catch {
      setNames((prev) =>
        prev.map((n) =>
          n.id === nameId ? { ...n, domainAvailable: 'unknown' as AvailabilityStatus } : n
        )
      )
    }
  }, [])

  // Check social handle availability for each name after generation
  const checkSocialAvailability = useCallback(async (nameId: string, handle: string) => {
    // Mark as "checking"
    setNames((prev) =>
      prev.map((n) =>
        n.id === nameId
          ? { ...n, twitterAvailable: 'checking' as AvailabilityStatus, instagramAvailable: 'checking' as AvailabilityStatus }
          : n
      )
    )

    try {
      const res = await fetch(`/api/check-social?handle=${encodeURIComponent(handle)}&platform=all`)
      const data = await res.json()

      setNames((prev) =>
        prev.map((n) =>
          n.id === nameId
            ? {
                ...n,
                twitterAvailable: (data.twitter?.available ? 'available' : 'taken') as AvailabilityStatus,
                instagramAvailable: (data.instagram?.available ? 'available' : 'taken') as AvailabilityStatus,
              }
            : n
        )
      )
    } catch {
      setNames((prev) =>
        prev.map((n) =>
          n.id === nameId
            ? { ...n, twitterAvailable: 'unknown' as AvailabilityStatus, instagramAvailable: 'unknown' as AvailabilityStatus }
            : n
        )
      )
    }
  }, [])

  // Trigger availability checks when new names appear (after generation completes)
  // Uses a ref to track which name IDs we've already started checking
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set())

  useEffect(() => {
    if (names.length === 0) return

    // Only check names that still have 'unknown' status and haven't been checked yet
    const namesToCheck = names.filter(
      (n) => n.domainAvailable === 'unknown' && !checkedIds.has(n.id)
    )

    if (namesToCheck.length === 0) return

    // Mark these as queued so we don't re-trigger
    setCheckedIds((prev) => {
      const next = new Set(prev)
      namesToCheck.forEach((n) => next.add(n.id))
      return next
    })

    // Stagger checks to avoid overwhelming APIs (500ms apart)
    namesToCheck.forEach((name, i) => {
      const domain = name.domainSuggestion || `${name.name.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`
      const handle = name.name.toLowerCase().replace(/[^a-z0-9_]/g, '').slice(0, 15)

      setTimeout(() => {
        checkDomainAvailability(name.id, domain)
        checkSocialAvailability(name.id, handle)
      }, i * 500)
    })
  }, [names, checkedIds, checkDomainAvailability, checkSocialAvailability])

  return (
    <>
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-brand-50 via-white to-purple-50" />
        <div className="absolute top-0 right-0 -translate-y-1/4 translate-x-1/4 w-96 h-96 bg-brand-200/30 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-0 translate-y-1/4 -translate-x-1/4 w-96 h-96 bg-purple-200/30 rounded-full blur-3xl" />

        <div className="relative mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-brand-100 px-4 py-1.5 text-sm font-medium text-brand-700">
              <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-brand-400 opacity-75" />
                <span className="relative inline-flex h-2 w-2 rounded-full bg-brand-500" />
              </span>
              AI-Powered Name Generation
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900">
              Generate the <span className="gradient-text">perfect name</span> for your business
            </h1>
            <p className="mt-3 text-base sm:text-lg text-slate-600 max-w-xl mx-auto">
              Describe your business idea and get unique, memorable names with brand kits — logo concepts, colors, taglines, and availability checks. Free to start.
            </p>

            {/* Trust badges */}
            <div className="mt-6 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-slate-500">
              <div className="flex items-center gap-1.5">
                <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                No signup required
              </div>
              <div className="flex items-center gap-1.5">
                <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                5 free generations
              </div>
              <div className="flex items-center gap-1.5">
                <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                Results in 30 seconds
              </div>
            </div>
          </div>

          {/* Generator Form */}
          <div className="mx-auto mt-10 max-w-2xl">
            <div className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 shadow-lg">
              <form onSubmit={handleGenerate} className="space-y-4">
                <div>
                  <label htmlFor="description" className="block text-sm font-medium text-slate-700 mb-1.5">
                    Describe your business idea <span className="text-brand-600">*</span>
                  </label>
                  <textarea
                    id="description"
                    rows={3}
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="e.g. A sustainable coffee shop in Brooklyn that sources fair-trade beans and offers community events..."
                    className="input-field resize-none"
                    required
                  />
                </div>

                <div>
                  <label htmlFor="industry" className="block text-sm font-medium text-slate-700 mb-1.5">
                    Industry <span className="text-slate-400 font-normal">(optional)</span>
                  </label>
                  <select
                    id="industry"
                    value={industry}
                    onChange={(e) => setIndustry(e.target.value)}
                    className="input-field"
                  >
                    <option value="">Select an industry</option>
                    {INDUSTRIES.map((ind) => (
                      <option key={ind} value={ind}>{ind}</option>
                    ))}
                  </select>
                </div>

                <button
                  type="submit"
                  disabled={loading || !description.trim()}
                  className="btn-primary w-full disabled:opacity-50 disabled:cursor-not-allowed text-base"
                >
                  {loading ? (
                    <span className="flex items-center justify-center gap-2">
                      <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24" fill="none">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                      </svg>
                      Generating names...
                    </span>
                  ) : (
                    <span className="flex items-center justify-center gap-2">
                      <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456z" />
                      </svg>
                      Generate Names — Free
                    </span>
                  )}
                </button>
              </form>

              {error && (
                <div className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-600">
                  {error}
                </div>
              )}
            </div>

            {/* Example prompts */}
            <div className="mt-6">
              <p className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-3 text-center">Try an example</p>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {EXAMPLE_PROMPTS.map((prompt) => (
                  <button
                    key={prompt.label}
                    type="button"
                    onClick={() => {
                      setDescription(prompt.text)
                      setHasGenerated(false)
                    }}
                    className="group rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-left text-sm text-slate-600 hover:border-brand-300 hover:bg-brand-50 hover:text-brand-700 transition-all duration-200"
                  >
                    <span className="mr-1.5">{prompt.emoji}</span>
                    <span className="font-medium text-slate-700 group-hover:text-brand-700">{prompt.label}</span>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Results */}
      {names.length > 0 && (
        <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-5xl">
            <NameResultsGrid
              names={names}
              onToggleFavorite={handleToggleFavorite}
            />
            <p className="mt-6 text-center text-sm text-slate-500">
              Click any name to see the full brand kit with logo, colors, and more.
            </p>
          </div>
        </section>
      )}

      {/* How it works — show below the fold */}
      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <p className="text-sm font-semibold text-brand-600 mb-3 tracking-wider uppercase">How It Works</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-slate-900">
            From idea to brand identity in three steps
          </h2>
        </div>

        <div className="grid gap-8 sm:grid-cols-3 max-w-4xl mx-auto">
          <div className="text-center">
            <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-100 text-brand-600 mb-4">
              <svg className="h-7 w-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
              </svg>
            </div>
            <h3 className="text-base font-semibold text-slate-900 mb-2">1. Describe your idea</h3>
            <p className="text-sm text-slate-500">Tell us about your business — the industry, vibe, target audience, or anything that inspires you.</p>
          </div>
          <div className="text-center">
            <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-purple-100 text-purple-600 mb-4">
              <svg className="h-7 w-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456z" />
              </svg>
            </div>
            <h3 className="text-base font-semibold text-slate-900 mb-2">2. Get tailored names</h3>
            <p className="text-sm text-slate-500">Our AI generates unique business names with meanings, styles, and brand personalities that match your vision.</p>
          </div>
          <div className="text-center">
            <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-green-100 text-green-600 mb-4">
              <svg className="h-7 w-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.59 14.37a6 6 0 01-5.84 7.58v-4.11m5.84-3.47a5.998 5.998 0 00-5.84-3.47v-4.11a6 6 0 015.84 7.58zm-5.84 0a6 6 0 01-5.84 7.58v-4.11M9.75 10.9a6 6 0 00-5.84 3.47v4.11a6 6 0 015.84-7.58z" />
              </svg>
            </div>
            <h3 className="text-base font-semibold text-slate-900 mb-2">3. Launch your brand</h3>
            <p className="text-sm text-slate-500">Unlock a full brand kit with logo concept, color palette, tagline, and domain availability — ready to use.</p>
          </div>
        </div>

        {/* CTA row */}
        <div className="mt-12 text-center">
          <a href="#generate-top" className="btn-primary px-8 py-3" onClick={(e) => { e.preventDefault(); document.getElementById('description')?.focus() }}>
            Try It Now — Free
          </a>
        </div>
      </section>

      {/* Social proof strip */}
      <section className="border-y border-slate-100 bg-slate-50/50">
        <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-8 text-center">
            <div>
              <p className="text-3xl font-bold gradient-text">50K+</p>
              <p className="mt-1 text-sm text-slate-500">Names Generated</p>
            </div>
            <div>
              <p className="text-3xl font-bold gradient-text">12K+</p>
              <p className="mt-1 text-sm text-slate-500">Happy Founders</p>
            </div>
            <div>
              <p className="text-3xl font-bold gradient-text">4.9/5</p>
              <p className="mt-1 text-sm text-slate-500">Average Rating</p>
            </div>
            <div>
              <p className="text-3xl font-bold gradient-text">&lt; 30s</p>
              <p className="mt-1 text-sm text-slate-500">Time to Results</p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="mx-auto max-w-3xl px-4 py-20 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <p className="text-sm font-semibold text-brand-600 mb-3 tracking-wider uppercase">FAQ</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-slate-900">
            Frequently asked questions
          </h2>
        </div>

        <div className="space-y-4">
          {GENERATE_FAQ.map((faq, i) => (
            <div key={i} className="rounded-2xl border border-slate-200 bg-white overflow-hidden">
              <button
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                className="w-full flex items-center justify-between px-6 py-4 text-left hover:bg-slate-50 transition-colors"
              >
                <span className="text-base font-semibold text-slate-900 pr-4">{faq.question}</span>
                <svg
                  className={`h-5 w-5 text-slate-400 flex-shrink-0 transition-transform duration-200 ${openFaq === i ? 'rotate-180' : ''}`}
                  fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
              </button>
              <div className={`accordion-content ${openFaq === i ? '[data-open="true"]' : ''}`} data-open={openFaq === i ? 'true' : 'false'}>
                <div className="px-6 pb-4">
                  <p className="text-sm text-slate-600 leading-relaxed">{faq.answer}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Generate-page FAQ Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: GENERATE_FAQ.map((faq) => ({
              '@type': 'Question',
              name: faq.question,
              acceptedAnswer: {
                '@type': 'Answer',
                text: faq.answer,
              },
            })),
          }),
        }}
      />

      {/* Bottom CTA */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-brand-600 to-purple-700" />
        <div className="relative mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-20 text-center">
          <h2 className="text-2xl sm:text-3xl font-bold text-white">
            Ready to find your perfect business name?
          </h2>
          <p className="mt-4 text-lg text-brand-100 max-w-lg mx-auto">
            Join thousands of founders who found their brand identity with BrandForge. Free to start — no credit card required.
          </p>
          <div className="mt-8">
            <a
              href="#generate-top"
              onClick={(e) => { e.preventDefault(); document.getElementById('description')?.focus() }}
              className="inline-flex items-center justify-center rounded-xl bg-white px-8 py-3.5 text-base font-semibold text-brand-700 shadow-lg hover:bg-slate-50 transition-all duration-200 hover:shadow-xl"
            >
              Generate Names — Free
              <svg className="ml-2 h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
              </svg>
            </a>
          </div>
        </div>
      </section>
    </>
  )
}

export default function GeneratePage() {
  return (
    <Suspense fallback={
      <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <div className="animate-pulse space-y-4">
            <div className="h-8 w-64 rounded bg-slate-200" />
            <div className="h-4 w-96 rounded bg-slate-200" />
            <div className="h-32 w-full rounded-2xl bg-slate-200" />
            <div className="h-12 w-full rounded bg-slate-200" />
          </div>
        </div>
      </div>
    }>
      <GeneratePageContent />
    </Suspense>
  )
}