'use client'

import { useState } from 'react'
import Link from 'next/link'

const PRICING_FAQ = [
  {
    q: 'Is BrandForge really free to use?',
    a: 'Yes! You can generate business names for free — 5 suggestions per search, unlimited searches, no credit card required. The free tier is perfect for brainstorming and finding names you love.',
  },
  {
    q: 'What exactly do I get with the Brand Kit Pro?',
    a: 'Brand Kit Pro unlocks the full brand identity for one name: an AI-generated logo concept, a custom 5-color palette with hex codes, a memorable tagline, typography recommendations, domain availability check across multiple TLDs, and social media handle availability. You also get a downloadable PDF brand guidelines document. All for $9 per brand kit.',
  },
  {
    q: 'What does "$9 per brand kit" mean?',
    a: 'You pay $9 each time you want to unlock the full brand kit for a name. There\'s no subscription — you only pay for the brand kits you actually want. Most founders find their perfect name in one or two sessions.',
  },
  {
    q: 'Can I see a brand kit before I buy?',
    a: 'Absolutely — check out our Examples page to see real brand kits generated by BrandForge. You can see exactly what you\'ll get: logo concepts, color palettes, taglines, and more.',
  },
  {
    q: 'Do I own the names and brand kits I generate?',
    a: 'Yes. All names and brand kits you generate are yours to use commercially — for business registration, trademarks, domains, marketing, anything. There are no licensing restrictions or ongoing fees from BrandForge.',
  },
  {
    q: 'What if I\'m not happy with my brand kit?',
    a: 'We offer a 14-day money-back guarantee. If you\'re not satisfied with your brand kit for any reason, contact us within 14 days of purchase for a full refund — no questions asked.',
  },
  {
    q: 'Is there a subscription or recurring charge?',
    a: 'No. BrandForge is pay-per-brand-kit at $9 each. There are no subscriptions, no recurring charges, and no hidden fees. You only pay when you\'re ready to unlock a brand identity.',
  },
  {
    q: 'How does BrandForge compare to hiring a branding agency?',
    a: 'A branding agency typically charges $5,000–$50,000+ and takes weeks. BrandForge gives you professional brand identity in seconds for $9. It\'s not meant to replace a full branding engagement — it\'s designed to give founders a complete, usable brand identity fast and affordable.',
  },
]

const COMPARISON_FEATURES = [
  { feature: 'Business name suggestions', free: '5 per search', pro: 'Unlimited' },
  { feature: 'Searches per day', free: 'Unlimited', pro: 'Unlimited' },
  { feature: 'Name meanings & styles', free: '✓', pro: '✓' },
  { feature: 'Favorite & compare names', free: 'Up to 10', pro: 'Unlimited' },
  { feature: 'AI logo concept', free: '—', pro: '✓' },
  { feature: 'Custom color palette (5 colors + hex codes)', free: '—', pro: '✓' },
  { feature: 'Brand tagline', free: '—', pro: '✓' },
  { feature: 'Typography recommendations', free: '—', pro: '✓' },
  { feature: 'Domain availability check', free: '—', pro: '✓ (.com, .io, .co + more)' },
  { feature: 'Social media handle check', free: '—', pro: '✓ (Twitter/X, Instagram)' },
  { feature: 'Brand kit PDF export', free: '—', pro: '✓' },
  { feature: 'Priority name generation', free: '—', pro: '✓' },
  { feature: 'Price', free: '$0 forever', pro: '$9 per brand kit' },
]

export default function PricingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null)

  return (
    <>
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-brand-50 via-white to-purple-50" />
        <div className="absolute top-0 right-0 -translate-y-1/4 translate-x-1/4 w-96 h-96 bg-brand-200/30 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-0 translate-y-1/4 -translate-x-1/4 w-96 h-96 bg-purple-200/30 rounded-full blur-3xl" />

        <div className="relative mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-brand-100 px-4 py-1.5 text-sm font-medium text-brand-700">
              <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-brand-400 opacity-75" />
                <span className="relative inline-flex h-2 w-2 rounded-full bg-brand-500" />
              </span>
              Simple, Transparent Pricing
            </div>
            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-slate-900">
              Start free,{' '}
              <span className="gradient-text">upgrade when you&apos;re ready</span>
            </h1>
            <p className="mt-4 text-lg text-slate-600 max-w-xl mx-auto">
              Try the name generator for free. Upgrade to unlock a complete brand kit — logo, colors, tagline, domain check, and more — for just $9.
            </p>

            {/* Trust signals */}
            <div className="mt-6 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm text-slate-500">
              <div className="flex items-center gap-1.5">
                <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                No credit card required
              </div>
              <div className="flex items-center gap-1.5">
                <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                14-day money-back guarantee
              </div>
              <div className="flex items-center gap-1.5">
                <svg className="h-4 w-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                No subscription needed
              </div>
            </div>
          </div>

          {/* Pricing cards */}
          <div className="mt-16 grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {/* Free tier */}
            <div className="card flex flex-col">
              <h3 className="text-lg font-semibold text-slate-900 mb-1">Free</h3>
              <p className="text-sm text-slate-500 mb-6">Perfect for brainstorming</p>
              <div className="mb-6">
                <span className="text-5xl font-bold text-slate-900">$0</span>
                <span className="text-slate-400 text-sm ml-1">/forever</span>
              </div>
              <ul className="space-y-3 mb-8 flex-1">
                {[
                  '5 name suggestions per search',
                  'Unlimited searches',
                  'Basic name meanings & styles',
                  'Save up to 10 favorites',
                  'No credit card required',
                  'Instant results',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-slate-600">
                    <svg className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                    {item}
                  </li>
                ))}
              </ul>
              <Link
                href="/generate"
                className="btn-secondary block text-center text-base py-3"
              >
                Get Started Free
              </Link>
            </div>

            {/* Pro tier */}
            <div className="relative flex flex-col rounded-2xl border-2 border-brand-500 bg-gradient-to-b from-brand-50/50 to-white p-8 shadow-xl ring-1 ring-brand-500/20">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-brand-600 text-white text-xs font-semibold px-4 py-1 rounded-full shadow-sm">
                Most Popular
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-1">Brand Kit Pro</h3>
              <p className="text-sm text-slate-500 mb-6">Full branding in one click</p>
              <div className="mb-6">
                <span className="text-5xl font-bold text-slate-900">$9</span>
                <span className="text-slate-400 text-sm ml-1">/brand kit</span>
              </div>
              <ul className="space-y-3 mb-8 flex-1">
                {[
                  'Unlimited name suggestions',
                  'AI logo concept & description',
                  'Custom color palette (5 colors + hex codes)',
                  'Brand tagline & copy',
                  'Typography recommendations',
                  'Domain availability check',
                  'Social media handle availability',
                  'Export full brand kit (PDF)',
                  'Priority name generation',
                  '14-day money-back guarantee',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-3 text-sm text-slate-600">
                    <svg className="w-5 h-5 text-brand-600 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                    {item}
                  </li>
                ))}
              </ul>
              <Link
                href="/generate"
                className="btn-primary block w-full text-center text-base py-3"
              >
                Upgrade to Pro — $9
              </Link>
            </div>
          </div>

          {/* Money-back guarantee banner */}
          <div className="mt-12 mx-auto max-w-3xl">
            <div className="rounded-2xl border border-green-200 bg-green-50 p-6 text-center">
              <div className="flex items-center justify-center gap-3 mb-2">
                <svg className="h-6 w-6 text-green-600" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
                </svg>
                <span className="text-base font-semibold text-green-800">14-Day Money-Back Guarantee</span>
              </div>
              <p className="text-sm text-green-700 max-w-xl mx-auto">
                Not happy with your brand kit? Contact us within 14 days for a full refund. No questions asked, no hassle.
              </p>
            </div>
          </div>

          {/* Enterprise note */}
          <p className="mt-6 text-center text-sm text-slate-400">
            Need team access, custom volume, or a white-label solution?{' '}
            <a href="mailto:hello@brandforge.ai" className="text-brand-600 hover:underline font-medium">
              Contact us
            </a>
          </p>
        </div>
      </section>

      {/* Feature comparison table */}
      <section className="py-20 sm:py-28 bg-white">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <p className="text-sm font-semibold text-brand-600 mb-3 tracking-wider uppercase">
              Compare Plans
            </p>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900">
              See exactly what you get
            </h2>
            <p className="mt-4 text-lg text-slate-500 max-w-xl mx-auto">
              The free tier is powerful on its own. Pro unlocks the complete brand identity.
            </p>
          </div>

          <div className="overflow-hidden rounded-2xl border border-slate-200 shadow-sm">
            <table className="w-full">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="px-6 py-4 text-left text-sm font-semibold text-slate-900">Feature</th>
                  <th className="px-6 py-4 text-center text-sm font-semibold text-slate-900">Free</th>
                  <th className="px-6 py-4 text-center text-sm font-semibold text-brand-600">Pro</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {COMPARISON_FEATURES.map((row, i) => (
                  <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-slate-50/30'}>
                    <td className="px-6 py-3.5 text-sm text-slate-700">{row.feature}</td>
                    <td className="px-6 py-3.5 text-sm text-center text-slate-600">
                      {row.free === '—' ? (
                        <span className="text-slate-300">—</span>
                      ) : row.free === '✓' ? (
                        <svg className="h-5 w-5 mx-auto text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                      ) : (
                        row.free
                      )}
                    </td>
                    <td className="px-6 py-3.5 text-sm text-center">
                      {row.pro === '✓' ? (
                        <svg className="h-5 w-5 mx-auto text-brand-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                      ) : (
                        <span className="font-medium text-brand-700">{row.pro}</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="mt-6 text-center">
            <Link href="/examples" className="text-brand-600 hover:text-brand-700 font-medium text-sm">
              See brand kit examples →
            </Link>
          </div>
        </div>
      </section>

      {/* Why $9? Value prop */}
      <section className="py-20 sm:py-24 bg-slate-50">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <p className="text-sm font-semibold text-brand-600 mb-3 tracking-wider uppercase">
              Why BrandForge Pro
            </p>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900">
              Professional branding for less than a domain
            </h2>
          </div>

          <div className="grid gap-8 sm:grid-cols-3">
            <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm">
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-100 text-brand-600">
                <svg className="h-7 w-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v12m-3-2.818l.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.242 0l.879.659M3 10.5h18M12 3v3m0 12v3" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2">$9, not $5,000+</h3>
              <p className="text-sm text-slate-500">
                A branding agency charges $5,000–$50,000. BrandForge gives you a complete brand identity for less than a coffee subscription.
              </p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm">
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-purple-100 text-purple-600">
                <svg className="h-7 w-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2">Seconds, not weeks</h3>
              <p className="text-sm text-slate-500">
                Instead of waiting weeks for design rounds, get a polished brand kit in seconds. Name, logo concept, colors, tagline — all at once.
              </p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm">
              <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-green-100 text-green-600">
                <svg className="h-7 w-7" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-slate-900 mb-2">Zero risk</h3>
              <p className="text-sm text-slate-500">
                Try the name generator free. Only pay when you find a name you love. And with our 14-day money-back guarantee, there&apos;s nothing to lose.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 sm:py-28 bg-white">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <p className="text-sm font-semibold text-brand-600 mb-3 tracking-wider uppercase">
              FAQ
            </p>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900">
              Pricing questions
            </h2>
            <p className="mt-4 text-slate-500 max-w-xl mx-auto">
              Everything you need to know about BrandForge pricing.
            </p>
          </div>

          <div className="space-y-3">
            {PRICING_FAQ.map((faq, i) => (
              <div
                key={i}
                className={`rounded-xl border overflow-hidden transition-colors duration-200 ${
                  openFaq === i
                    ? 'border-brand-200 bg-white shadow-sm'
                    : 'border-slate-200 bg-white hover:border-slate-300'
                }`}
              >
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between p-5 text-left transition-colors"
                >
                  <span className={`font-medium pr-4 transition-colors ${
                    openFaq === i ? 'text-brand-700' : 'text-slate-900'
                  }`}>
                    {faq.q}
                  </span>
                  <svg
                    className={`w-5 h-5 flex-shrink-0 transition-all duration-300 ${
                      openFaq === i ? 'rotate-180 text-brand-500' : 'text-slate-400'
                    }`}
                    fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                <div
                  className="accordion-content"
                  data-open={openFaq === i ? 'true' : 'false'}
                >
                  <div>
                    <div className="px-5 pb-5 text-sm text-slate-600 leading-relaxed">
                      {faq.a}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Bottom CTA */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-brand-600 to-purple-700" />
        <div className="relative mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-20 text-center">
          <h2 className="text-2xl sm:text-3xl font-bold text-white">
            Ready to build your brand?
          </h2>
          <p className="mt-4 text-lg text-brand-100 max-w-lg mx-auto">
            Start with free name generation, then unlock a complete brand kit for just $9. No subscriptions, no surprises.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/generate"
              className="inline-flex items-center justify-center rounded-xl bg-white px-8 py-3.5 text-base font-semibold text-brand-700 shadow-lg hover:bg-slate-50 transition-all duration-200 hover:shadow-xl"
            >
              Start Free — No Credit Card
              <svg className="ml-2 h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
              </svg>
            </Link>
            <Link
              href="/examples"
              className="inline-flex items-center justify-center rounded-xl border-2 border-white/30 px-8 py-3.5 text-base font-semibold text-white hover:bg-white/10 transition-all duration-200"
            >
              See Brand Kit Examples
            </Link>
          </div>
        </div>
      </section>

      {/* Pricing page Breadcrumb Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'BreadcrumbList',
            itemListElement: [
              {
                '@type': 'ListItem',
                position: 1,
                name: 'Home',
                item: 'https://brandforge-phi-pearl.vercel.app',
              },
              {
                '@type': 'ListItem',
                position: 2,
                name: 'Pricing',
                item: 'https://brandforge-phi-pearl.vercel.app/pricing',
              },
            ],
          }),
        }}
      />

      {/* Pricing page FAQ Schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: PRICING_FAQ.map((faq) => ({
              '@type': 'Question',
              name: faq.q,
              acceptedAnswer: {
                '@type': 'Answer',
                text: faq.a,
              },
            })),
          }),
        }}
      />
    </>
  )
}