import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { SITE_URL, SITE_NAME, SITE_DESCRIPTION } from '@/lib/site-config'
import './globals.css'

const inter = Inter({ subsets: ['latin'], display: 'swap', adjustFontFallback: true })

// Dynamic import SupabaseProvider to reduce initial JS bundle by ~46KB
// Auth is only needed on /brand-kit and /generate pages, so lazy-load it
const SupabaseProvider = dynamic(
  () => import('@/components/supabase-provider').then(mod => ({ default: mod.SupabaseProvider })),
  { ssr: false }
)

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: 'BrandForge — Free AI Business Name Generator & Brand Kit Creator',
  description: 'Generate unique business names instantly with AI. Get complete brand kits with logo concepts, color palettes, taglines, and domain availability. Free to start — no credit card required.',
  keywords: [
    'business name generator',
    'brand name generator',
    'brand name ideas',
    'AI name generator',
    'company name ideas',
    'startup name generator',
    'brand kit',
    'logo generator',
    'ai naming',
    'startup names',
    'brand identity',
    'company name ideas',
    'domain name checker',
    'brand kit creator',
    'free business name generator',
    'online name generator',
    'business naming tool',
    'catchy business names',
    'brand kit examples',
    'LLC name ideas',
    'creative brand names',
    'business name ideas by industry',
    'brand name generator free',
    'brand naming guide',
    'best brand name generator',
    'how to choose a brand name',
    'company name checker',
    'unique business names',
    'product naming guide',
    'brandforge vs namelix',
    'best business name generator',
    'naming tool comparison',
    'AI brand name generator comparison',
    'is brand name generator free',
    'how to come up with a business name',
    'business name availability check',
    'what makes a good brand name',
    'brand name ideas by industry',
    'free AI brand kit',
    'how to build a brand identity',
    'brand identity guide',
    'brand identity from scratch',
    'create a brand identity',
    'brand identity for startups',
    'brand kit template',
    'cool business names',
    'cool brand names',
    'brand kit pricing',
    'business name generator pricing',
    'AI brand kit price',
    'brand identity cost',
    'startup name generator',
    'startup name ideas',
    'tech startup names',
    'restaurant name generator',
    'restaurant name ideas',
    'restaurant names',
    'creative restaurant names',
    'unique restaurant names',
    'catchy restaurant names',
    'best restaurant names',
    'how to name a restaurant',
    'restaurant naming tips',
    'cool restaurant names',
    'fine dining restaurant names',
    'casual restaurant names',
    'restaurant name ideas 2026',
    'bistro name ideas',
    'café name ideas',
    'diner name ideas',
    'elegant restaurant names',
    'modern restaurant names',
    'restaurant brand names',
    'opening a restaurant name ideas',
    'cafe name generator',
    'food business name ideas',
    'fitness brand name generator',
    'gym name generator',
    'fitness brand names',
    'gym name ideas',
    'real estate name generator',
    'real estate business names',
    'property name ideas',
    'realty name generator',
    'photography name generator',
    'photography business names',
    'photography studio names',
    'photographer name ideas',
    'photography brand names',
    'photo studio name ideas',
    'how to name a photography business',
    'creative photography names',
    'wedding photography names',
    'photography business name ideas',
    'portrait photography names',
    'photography company names',
    'best photography business names',
    'photography naming tips',
    'photography branding ideas',
    'photo business names',
    'photography name ideas 2026',
    'catchy photography names',
    'photography brand naming',
    'photo studio brand names',
    'beauty name generator',
    'beauty business names',
    'beauty salon names',
    'beauty brand name ideas',
    'fashion name generator',
    'fashion brand names',
    'clothing brand names',
    'fashion business names',
    'food truck name generator',
    'food truck names',
    'food truck name ideas',
    'food cart name generator',
    'food truck business names',
    'tech name generator',
    'tech startup names',
    'SaaS name generator',
    'tech company names',
    'app name generator',
    'consulting name generator',
    'consulting business names',
    'consulting firm names',
    'agency name generator',
    'podcast name generator',
    'podcast name ideas',
    'podcast names',
    'show name generator',
    'coaching name generator',
    'coaching business names',
    'life coach name ideas',
    'coaching practice names',
    'nonprofit name generator',
    'nonprofit organization names',
    'charity name generator',
    'nonprofit name ideas',
    'foundation name generator',
    'craft name generator',
    'handmade business names',
    'artisan name ideas',
    'Etsy shop name generator',
    'craft business names',
    'education name generator',
    'tutoring business names',
    'course name ideas',
    'EdTech company names',
    'online academy names',
    'yoga name generator',
    'yoga studio names',
    'yoga business names',
    'wellness business names',
    'meditation business names',
    'coffee name generator',
    'coffee shop names',
    'café name generator',
    'coffee business names',
    'coffee roastery names',
    'music name generator',
    'band name generator',
    'record label name generator',
    'music business names',
    'music studio name ideas',
    'DJ name generator',
    'wedding name generator',
    'wedding business names',
    'wedding venue name ideas',
    'wedding planning business names',
    'wedding company names',
    'bridal business name ideas',
    'cleaning business name generator',
    'cleaning company names',
    'maid service name ideas',
    'janitorial business names',
    'cleaning service names',
    'house cleaning business names',
    'commercial cleaning names',
    'pet name generator',
    'pet business names',
    'pet store names',
    'pet grooming business names',
    'dog grooming name ideas',
    'veterinary clinic names',
    'pet sitting business names',
    'animal business names',
    'brand name generator reviews',
    'business name generator reviews',
    'AI name generator reviews',
    'brand kit reviews',
    'brand naming success stories',
    'small business name generator',
    'small business name ideas',
    'small business names',
    'how to name a small business',
    'small business naming',
    'best small business names',
    'creative small business names',
    'small business name ideas 2026',
    'naming your small business',
    'small business brand names',
    'landscaping name generator',
    'landscaping business names',
    'lawn care name ideas',
    'landscape company names',
    'lawn care business names',
    'landscaping company name ideas',
    'lawn service name generator',
    'landscape design business names',
    'yard maintenance business names',
    'garden design business names',
    'hardscape business names',
    'salon name generator',
    'hair salon name ideas',
    'beauty salon names',
    'barber shop name ideas',
    'salon name ideas',
    'hair salon names',
    'barbershop name generator',
    'nail salon name ideas',
    'spa name generator',
    'hair stylist business names',
    'cosmetology name ideas',
    'salon branding ideas',
    'construction name generator',
    'construction business names',
    'contractor name ideas',
    'builder name generator',
    'construction company names',
    'general contractor names',
    'home builder name ideas',
    'remodeling business names',
    'construction brand names',
    'building company names',
    'roofing business names',
    'excavation company names',
    // Marketing agency keywords
    'marketing agency name generator',
    'marketing agency names',
    'digital marketing agency name ideas',
    'ad agency name generator',
    'advertising agency names',
    'marketing firm name ideas',
    'creative agency name generator',
    'branding agency names',
    'digital agency names',
    'marketing company name ideas',
    'growth agency name ideas',
    'media agency names',
    // Auto repair shop name generator keywords
    'auto repair shop name generator',
    'auto repair shop names',
    'mechanic shop names',
    'car repair business names',
    'garage name ideas',
    'auto shop name generator',
    'car repair shop names',
    'mechanic business names',
    'auto repair business names',
    'garage names',
    'automotive shop names',
    'car garage names',
    'automotive business names',
    'mechanic garage names',
    'how to name an auto repair shop',
    // Coffee shop name generator keywords
    'coffee shop name generator',
    'coffee shop names',
    'café name ideas',
    'coffee brand names',
    'coffee shop name ideas',
    'café name generator',
    'coffee business names',
    'coffee house names',
    'coffee roaster names',
    'café business names',
    'best coffee shop names',
    'creative café names',
    'unique coffee shop names',
    'catchy coffee names',
    'how to name a coffee shop',
    'coffee shop naming tips',
    'espresso bar names',
    'coffee stand names',
    'how to choose a brand name',
    'choosing a brand name',
    'how to pick a brand name',
    'brand name tips',
    'brand naming process',
    'how to come up with a brand name',
    'what makes a good brand name',
    'brand name decision framework',
    'naming your business',
    'brand name strategy',
    'brand name checklist',
    'brand name validation',
    // Brand naming guide keywords
    'brand naming guide',
    'how to pick a brand name',
    'brand name tips',
    'brand naming tips',
    'brand naming strategies',
    'brand naming principles',
    'brand name best practices',
    'naming your brand',
    'brand naming checklist',
    'tips for naming a brand',
    'brand name guide 2026',
    // Business name generator blog keywords
    'business name ideas 2026',
    'AI business name generator',
    'how to name a business',
    'generate business name',
    'creative business names',
    'business name checker',
    // Company name generator blog keywords
    'company name generator',
    'free company name generator',
    'company name ideas',
    'company names',
    'company name ideas 2026',
    'best company name generator',
    'AI company name generator',
    'how to name a company',
    'company naming tool',
    'corporate name generator',
    'company name checker',
    'startup company names',
    'LLC name generator',
    'inc name ideas',
    'generate company name',
    // LLC naming guide keywords
    'LLC naming guide',
    'how to name an LLC',
    'LLC name requirements',
    'LLC name rules',
    'DBA name',
    'fictitious business name',
    'LLC name availability',
    'LLC naming rules by state',
    // Brand identity keywords
    'how to build a brand identity',
    'brand identity guide',
    'brand identity from scratch',
    'create a brand identity',
    'brand identity for startups',
    'brand identity cost',
    'brand identity elements',
    // Startup naming mistakes keywords
    'startup naming mistakes',
    'naming mistakes to avoid',
    'common naming mistakes',
    'bad business names',
    // Catchy business names keywords
    'catchy business names',
    'catchy name ideas',
    'creative business names',
    'memorable business names',
    'catchy brand names',
    // Creative brand names keywords
    'creative brand names',
    'creative naming ideas',
    'unique brand names',
    'portmanteau brand names',
    // Unique brand names blog keywords
    'unique brand names',
    'standout brand names',
    'unique business name ideas',
    'how to create a unique brand name',
    'memorable brand names',
    'distinctive brand names',
    'one of a kind brand names',
    'unique brand name ideas 2026',
    'creative unique brand names',
    'uncommon brand names',
    'original brand names',
    'brand names that stand out',
    'unique company names',
    'unique startup names',
    'rare brand names',
    'inventive brand names',
    // Free brand name generator keywords
    'free brand name generator',
    'free name generator',
    'best free name generator',
    'free company name generator',
    'brand name generator no cost',
    'free naming tool',
    // App name generator keywords
    'app name generator',
    'app name ideas',
    'mobile app name generator',
    'SaaS name generator',
    'how to name an app',
    'app naming guide',
    'app name ideas 2026',
    'best app names',
    'creative app names',
    'cool app names',
    'app name ideas for startups',
    'mobile app naming',
    'how to come up with an app name',
    'app name brainstorming',
    'unique app names',
    // Product name generator blog keywords
    'product name generator',
    'product name ideas',
    'product naming tool',
    'free product name generator',
    'AI product name generator',
    'how to name a product',
    'product name ideas 2026',
    'creative product names',
    'cool product names',
    'product name brainstorming',
    'best product names',
    'product naming guide',
    'SaaS product name generator',
    'app product name ideas',
    'product naming strategies',
    // Startup name ideas keywords
    'startup name ideas',
    'startup names',
    'cool startup names',
    'creative startup names',
    'tech startup name ideas',
    'startup naming',
    'how to name a startup',
    'best startup names',
    'unique startup names',
    'startup name ideas 2026',
    'startup company name ideas',
    'SaaS startup names',
    'startup naming guide',
    'good startup names',
    // How to come up with a business name keywords
    'how to come up with a business name',
    'coming up with a business name',
    'ways to come up with a business name',
    'business name brainstorming',
    'how to brainstorm a business name',
    'how to think of a business name',
    'creative ways to name a business',
    'how to create a business name',
    'business name ideas',
    'how to find a business name',
    'tips for naming a business',
    'naming your business guide',
    'good business name ideas',
    // LLC name generator keywords
    'LLC name generator',
    'LLC name ideas',
    'LLC naming rules',
    'LLC name availability',
    'LLC name checker',
    'how to name an LLC',
    'best LLC names',
    'creative LLC names',
    'LLC business names',
    'free LLC name generator',
    'AI LLC name generator',
    'LLC naming guide',
    'unique LLC names',
    'cool LLC names',
    'LLC name ideas 2026',
    // Store name generator keywords
    'store name generator',
    'store name ideas',
    'shop name ideas',
    'online store name generator',
    'boutique name ideas',
    'retail store names',
    'how to name a store',
    'store names',
    'creative store names',
    'cool store names',
    'clothing store name ideas',
    'gift shop name ideas',
    'store name ideas 2026',
    'unique store names',
    'best store names',
    // Domain name generator keywords
    'domain name generator',
    'domain name availability',
    'domain name checker',
    'domain name ideas',
    'free domain name generator',
    'AI domain name generator',
    'check domain availability',
    'domain name search',
    'brand name domain checker',
    'available domain names',
    'domain finder',
    'how to pick a domain name',
    'best domain name generator',
    'business domain name generator',
    'domain name ideas 2026',
    // Clothing brand name generator keywords
    'clothing brand name generator',
    'clothing brand name ideas',
    'clothing brand names',
    'fashion brand name ideas',
    'apparel brand name generator',
    'how to name a clothing brand',
    'clothing brand names 2026',
    'creative clothing brand names',
    'unique clothing brand names',
    'cool clothing brand names',
    'clothing line name generator',
    'best clothing brand names',
    'streetwear brand name ideas',
    'boutique name ideas',
    'clothing brand name ideas 2026',
    // Construction company name generator keywords
    'construction company name generator',
    'construction company names',
    'construction business names',
    'contractor name ideas',
    'construction name ideas',
    'builder name generator',
    'general contractor names',
    'construction brand names',
    'home builder name ideas',
    'remodeling company names',
    'roofing company names',
    'excavation company names',
    'best construction company names',
    'creative construction names',
    'catchy construction names',
    'construction company name ideas 2026',
    'how to name a construction company',
    'construction branding ideas',
    'building company names',
    'construction naming tips',
    // YouTube channel name generator keywords
    'youtube channel name generator',
    'youtube channel name ideas',
    'youtube channel names',
    'how to name a youtube channel',
    'youtube name ideas',
    'creative youtube channel names',
    'best youtube channel names',
    'cool youtube channel names',
    'youtube channel name ideas 2026',
    'unique youtube channel names',
    'youtube channel naming tips',
    'good youtube channel names',
    'vlog name ideas',
    'youtube brand name generator',
    'catchy youtube channel names',
    // Podcast name generator keywords
    'podcast name generator',
    'podcast name ideas',
    'podcast names',
    'how to name a podcast',
    'podcast naming tips',
    'creative podcast names',
    'best podcast names',
    'cool podcast names',
    'podcast name ideas 2026',
    'unique podcast names',
    'podcast show name ideas',
    'podcast title generator',
    'catchy podcast names',
    'podcast branding guide',
    'podcast naming guide',
    // Brand name availability checker keywords
    'brand name availability checker',
    'check brand name availability',
    'brand name availability',
    'is my brand name available',
    'brand name checker',
    'brand name availability search',
    'how to check if a brand name is taken',
    'verify brand name availability',
    'brand name availability tool',
    'check if business name is available',
    'brand name availability checker free',
    'brand name domain availability',
    'trademark name availability check',
    'brand name search availability',
    'brand name availability 2026',
    // Blog name generator keywords
    'blog name generator',
    'blog name ideas',
    'blog names',
    'how to name a blog',
    'blog naming tips',
    'creative blog names',
    'best blog names',
    'cool blog names',
    'blog name ideas 2026',
    'unique blog names',
    'blog title generator',
    'good blog names',
    'catchy blog names',
    'lifestyle blog names',
    'blog name ideas for beginners',
    // SaaS name generator keywords
    'SaaS name generator',
    'SaaS name ideas',
    'SaaS startup names',
    'software as a service name generator',
    'how to name a SaaS company',
    'SaaS naming tips',
    'creative SaaS names',
    'best SaaS names',
    'cool SaaS names',
    'SaaS name ideas 2026',
    'unique SaaS names',
    'SaaS product name generator',
    'good SaaS names',
    'catchy SaaS names',
    'tech startup name ideas',
    'cloud software names',
    'app name ideas for SaaS',
    'SaaS brand names',
    'micro SaaS name ideas',
    'B2B SaaS names',
    // Nail salon name generator keywords
    'nail salon name generator',
    'nail salon name ideas',
    'nail salon names',
    'nail business names',
    'how to name a nail salon',
    'nail salon naming tips',
    'creative nail salon names',
    'best nail salon names',
    'cool nail salon names',
    'unique nail salon names',
    'nail bar name ideas',
    'nail spa name ideas',
    'nail studio names',
    'nail shop names',
    'manicure salon names',
    'pedicure salon names',
    'nail business name generator',
    'catchy nail salon names',
    'nail salon name ideas 2026',
    'good nail salon names',
    // Bakery name generator keywords
    'bakery name generator',
    'bakery name ideas',
    'bakery names',
    'how to name a bakery',
    'bakery naming tips',
    'creative bakery names',
    'best bakery names',
    'cool bakery names',
    'unique bakery names',
    'bakery name ideas 2026',
    'catchy bakery names',
    'bake shop name ideas',
    'bakery business names',
    'pastry shop names',
    'bread bakery names',
    'cake shop name ideas',
    'cupcake bakery names',
    'artisan bakery names',
    'bakery brand names',
    // Florist name generator keywords
    'florist name generator',
    'flower shop names',
    'florist business names',
    'floral business names',
    'florist name ideas',
    'flower shop name ideas',
    'floral design names',
    'flower business names',
    'how to name a flower shop',
    'florist naming guide',
    'flower boutique names',
    'flower studio names',
    'floral studio names',
    'wedding florist names',
    'flower delivery names',
    'plant shop names',
    'succulent shop names',
    'dried flower business names',
    'boutique florist names',
    'florist brand names',
    'creative flower shop names',
    'best florist names',
    'unique flower shop names',
    'florist name ideas 2026',
    'catchy flower shop names',
    'home bakery names',
    // Fitness brand name generator keywords
    'fitness brand name generator',
    'fitness brand name ideas',
    'gym name ideas',
    'fitness business names',
    'workout brand names',
    'fitness brand names',
    'gym name generator',
    'fitness company names',
    'how to name a fitness brand',
    'fitness naming tips',
    'creative fitness names',
    'best fitness brand names',
    'cool fitness names',
    'unique fitness brand names',
    'fitness brand name ideas 2026',
    'catchy fitness names',
    'personal training brand names',
    'fitness studio name ideas',
    'gym brand names',
    'workout brand name ideas',
    // Catering name generator keywords
    'catering name generator',
    'catering business names',
    'catering company names',
    'catering name ideas',
    'event catering names',
    'food catering business names',
    'how to name a catering business',
    'catering brand names',
    'catering company name ideas',
    'wedding catering names',
    'corporate catering names',
    'private chef business names',
    'catering business name ideas 2026',
    'catering service names',
    'best catering names',
    'unique catering business names',
    'catering startup names',
    'mobile catering names',
    'catering brand name ideas',
    'creative catering names',
    // Real estate brand name generator keywords
    'real estate brand name generator',
    'real estate business names',
    'real estate company names',
    'property name ideas',
    'realty name ideas',
    'real estate brand names',
    'real estate agency names',
    'real estate group names',
    'how to name a real estate business',
    'real estate naming tips',
    'creative real estate names',
    'best real estate brand names',
    'luxury real estate names',
    'property management name ideas',
    'real estate name ideas 2026',
    'catchy real estate names',
    'real estate brokerage names',
    'real estate firm names',
    'commercial real estate names',
    'real estate team names',
    // Salon brand name generator keywords
    'salon name generator',
    'salon name ideas',
    'hair salon names',
    'beauty salon names',
    'hair salon name ideas',
    'barber shop name ideas',
    'barbershop name generator',
    'spa name generator',
    'hair stylist business names',
    'cosmetology name ideas',
    'salon branding ideas',
    'best salon names',
    'creative salon names',
    'unique salon names',
    'catchy salon names',
    'salon name ideas 2026',
    'how to name a salon',
    'salon naming tips',
    'hair salon branding',
    'beauty salon name ideas',
  ],
  openGraph: {
    title: 'BrandForge — Free AI Business Name Generator & Brand Kit',
    description: 'Generate unique business names with complete brand kits — logo concepts, color palettes, taglines, and domain availability. Free to start, no credit card required.',
    url: SITE_URL,
    siteName: 'BrandForge',
    type: 'website',
    locale: 'en_US',
    images: [
      {
        url: '/opengraph-image',
        width: 1200,
        height: 630,
        alt: 'BrandForge — AI Business Name Generator & Brand Kit',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BrandForge — Free AI Business Name Generator & Brand Kit',
    description: 'Generate unique business names with complete brand kits — logos, colors, taglines, domain checks. Free to start.',
    images: ['/opengraph-image'],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: SITE_URL,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <SupabaseProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </SupabaseProvider>
      </body>
    </html>
  )
}