import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SupabaseProvider } from '@/components/supabase-provider'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  metadataBase: new URL('https://brandforge-phi-pearl.vercel.app'),
  title: 'BrandForge — Free AI Business Name Generator & Brand Kit Creator',
  description: 'Generate unique business names instantly with AI. Get complete brand kits with logo concepts, color palettes, taglines, and domain availability. Free to start — no credit card required.',
  keywords: [
    'business name generator',
    'brand name generator',
    'brand name ideas',
    'AI name generator',
    'company name ideas',
    'startup name generator',
    'brand kit',
    'logo generator',
    'ai naming',
    'startup names',
    'brand identity',
    'company name ideas',
    'domain name checker',
    'brand kit creator',
    'free business name generator',
    'online name generator',
    'business naming tool',
    'catchy business names',
    'brand kit examples',
    'LLC name ideas',
    'creative brand names',
    'business name ideas by industry',
    'brand name generator free',
    'brand naming guide',
    'best brand name generator',
    'how to choose a brand name',
    'company name checker',
    'unique business names',
    'product naming guide',
    'brandforge vs namelix',
    'best business name generator',
    'naming tool comparison',
    'AI brand name generator comparison',
    'is brand name generator free',
    'how to come up with a business name',
    'business name availability check',
    'what makes a good brand name',
    'brand name ideas by industry',
    'free AI brand kit',
    'how to build a brand identity',
    'brand identity guide',
    'brand identity from scratch',
    'create a brand identity',
    'brand identity for startups',
    'brand kit template',
    'cool business names',
    'cool brand names',
    'brand kit pricing',
    'business name generator pricing',
    'AI brand kit price',
    'brand identity cost',
    'startup name generator',
    'startup name ideas',
    'tech startup names',
    'restaurant name generator',
    'restaurant name ideas',
    'cafe name generator',
    'food business name ideas',
    'fitness brand name generator',
    'gym name generator',
    'fitness brand names',
    'gym name ideas',
    'real estate name generator',
    'real estate business names',
    'property name ideas',
    'realty name generator',
    'photography name generator',
    'photography business names',
    'photography studio names',
    'photographer name ideas',
    'beauty name generator',
    'beauty business names',
    'beauty salon names',
    'beauty brand name ideas',
    'fashion name generator',
    'fashion brand names',
    'clothing brand names',
    'fashion business names',
    'food truck name generator',
    'food truck names',
    'food truck name ideas',
    'food cart name generator',
    'food truck business names',
    'tech name generator',
    'tech startup names',
    'SaaS name generator',
    'tech company names',
    'app name generator',
    'consulting name generator',
    'consulting business names',
    'consulting firm names',
    'agency name generator',
    'podcast name generator',
    'podcast name ideas',
    'podcast names',
    'show name generator',
    'coaching name generator',
    'coaching business names',
    'life coach name ideas',
    'coaching practice names',
    'nonprofit name generator',
    'nonprofit organization names',
    'charity name generator',
    'nonprofit name ideas',
    'foundation name generator',
    'craft name generator',
    'handmade business names',
    'artisan name ideas',
    'Etsy shop name generator',
    'craft business names',
    'education name generator',
    'tutoring business names',
    'course name ideas',
    'EdTech company names',
    'online academy names',
    'yoga name generator',
    'yoga studio names',
    'yoga business names',
    'wellness business names',
    'meditation business names',
    'coffee name generator',
    'coffee shop names',
    'café name generator',
    'coffee business names',
    'coffee roastery names',
    'music name generator',
    'band name generator',
    'record label name generator',
    'music business names',
    'music studio name ideas',
    'DJ name generator',
    'wedding name generator',
    'wedding business names',
    'wedding venue name ideas',
    'wedding planning business names',
    'wedding company names',
    'bridal business name ideas',
    'cleaning business name generator',
    'cleaning company names',
    'maid service name ideas',
    'janitorial business names',
    'cleaning service names',
    'house cleaning business names',
    'commercial cleaning names',
    'pet name generator',
    'pet business names',
    'pet store names',
    'pet grooming business names',
    'dog grooming name ideas',
    'veterinary clinic names',
    'pet sitting business names',
    'animal business names',
    'brand name generator reviews',
    'business name generator reviews',
    'AI name generator reviews',
    'brand kit reviews',
    'brand naming success stories',
    'small business name generator',
    'small business name ideas',
    'small business names',
    'how to name a small business',
    'small business naming',
    'best small business names',
    'creative small business names',
    'small business name ideas 2026',
    'naming your small business',
    'small business brand names',
    'landscaping name generator',
    'landscaping business names',
    'lawn care name ideas',
    'landscape company names',
    'lawn care business names',
    'landscaping company name ideas',
    'lawn service name generator',
    'landscape design business names',
    'yard maintenance business names',
    'garden design business names',
    'hardscape business names',
    'salon name generator',
    'hair salon name ideas',
    'beauty salon names',
    'barber shop name ideas',
    'salon name ideas',
    'hair salon names',
    'barbershop name generator',
    'nail salon name ideas',
    'spa name generator',
    'hair stylist business names',
    'cosmetology name ideas',
    'salon branding ideas',
    'construction name generator',
    'construction business names',
    'contractor name ideas',
    'builder name generator',
    'construction company names',
    'general contractor names',
    'home builder name ideas',
    'remodeling business names',
    'construction brand names',
    'building company names',
    'roofing business names',
    'excavation company names',
    // Marketing agency keywords
    'marketing agency name generator',
    'marketing agency names',
    'digital marketing agency name ideas',
    'ad agency name generator',
    'advertising agency names',
    'marketing firm name ideas',
    'creative agency name generator',
    'branding agency names',
    'digital agency names',
    'marketing company name ideas',
    'growth agency name ideas',
    'media agency names',
    'how to choose a brand name',
    'choosing a brand name',
    'how to pick a brand name',
    'brand name tips',
    'brand naming process',
    'how to come up with a brand name',
    'what makes a good brand name',
    'brand name decision framework',
    'naming your business',
    'brand name strategy',
    'brand name checklist',
    'brand name validation',
    // Business name generator blog keywords
    'business name ideas 2026',
    'AI business name generator',
    'how to name a business',
    'generate business name',
    'creative business names',
    'business name checker',
    // Company name generator blog keywords
    'company name generator',
    'free company name generator',
    'company name ideas',
    'company names',
    'company name ideas 2026',
    'best company name generator',
    'AI company name generator',
    'how to name a company',
    'company naming tool',
    'corporate name generator',
    'company name checker',
    'startup company names',
    'LLC name generator',
    'inc name ideas',
    'generate company name',
    // LLC naming guide keywords
    'LLC naming guide',
    'how to name an LLC',
    'LLC name requirements',
    'LLC name rules',
    'DBA name',
    'fictitious business name',
    'LLC name availability',
    'LLC naming rules by state',
    // Brand identity keywords
    'how to build a brand identity',
    'brand identity guide',
    'brand identity from scratch',
    'create a brand identity',
    'brand identity for startups',
    'brand identity cost',
    'brand identity elements',
    // Startup naming mistakes keywords
    'startup naming mistakes',
    'naming mistakes to avoid',
    'common naming mistakes',
    'bad business names',
    // Catchy business names keywords
    'catchy business names',
    'catchy name ideas',
    'creative business names',
    'memorable business names',
    'catchy brand names',
    // Creative brand names keywords
    'creative brand names',
    'creative naming ideas',
    'unique brand names',
    'portmanteau brand names',
    // Free brand name generator keywords
    'free brand name generator',
    'free name generator',
    'best free name generator',
    'free company name generator',
    'brand name generator no cost',
    'free naming tool',
    // App name generator keywords
    'app name generator',
    'app name ideas',
    'mobile app name generator',
    'SaaS name generator',
    'how to name an app',
    'app naming guide',
    'app name ideas 2026',
    'best app names',
    'creative app names',
    'cool app names',
    'app name ideas for startups',
    'mobile app naming',
    'how to come up with an app name',
    'app name brainstorming',
    'unique app names',
    // Startup name ideas keywords
    'startup name ideas',
    'startup names',
    'cool startup names',
    'creative startup names',
    'tech startup name ideas',
    'startup naming',
    'how to name a startup',
    'best startup names',
    'unique startup names',
    'startup name ideas 2026',
    'startup company name ideas',
    'SaaS startup names',
    'startup naming guide',
    'good startup names',
  ],
  openGraph: {
    title: 'BrandForge — Free AI Business Name Generator & Brand Kit',
    description: 'Generate unique business names with complete brand kits — logo concepts, color palettes, taglines, and domain availability. Free to start, no credit card required.',
    url: 'https://brandforge-phi-pearl.vercel.app',
    siteName: 'BrandForge',
    type: 'website',
    locale: 'en_US',
    images: [
      {
        url: '/opengraph-image',
        width: 1200,
        height: 630,
        alt: 'BrandForge — AI Business Name Generator & Brand Kit',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'BrandForge — Free AI Business Name Generator & Brand Kit',
    description: 'Generate unique business names with complete brand kits — logos, colors, taglines, domain checks. Free to start.',
    images: ['/opengraph-image'],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: 'https://brandforge-phi-pearl.vercel.app',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <SupabaseProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </SupabaseProvider>
      </body>
    </html>
  )
}