import type { Metadata } from 'next'
import { LegalPage } from '@/components/LegalPage'

export const metadata: Metadata = {
  title: 'Terms of Service — BrandForge',
  description: 'BrandForge Terms of Service. Read our terms governing the use of our AI business name generator and brand kit creation services.',
  openGraph: {
    title: 'Terms of Service — BrandForge',
    description: 'Terms governing the use of BrandForge AI business name generator and brand kit services.',
    url: 'https://brandforge-phi-pearl.vercel.app/terms',
    siteName: 'BrandForge',
    type: 'website',
  },
  robots: { index: true, follow: true },
  alternates: { canonical: 'https://brandforge-phi-pearl.vercel.app/terms' },
}

export default function TermsPage() {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebPage',
        name: 'Terms of Service',
        description: 'BrandForge Terms of Service — terms governing the use of our AI business name generator and brand kit services.',
        url: 'https://brandforge-phi-pearl.vercel.app/terms',
        isPartOf: {
          '@type': 'WebSite',
          name: 'BrandForge',
          url: 'https://brandforge-phi-pearl.vercel.app',
        },
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://brandforge-phi-pearl.vercel.app' },
          { '@type': 'ListItem', position: 2, name: 'Terms of Service', item: 'https://brandforge-phi-pearl.vercel.app/terms' },
        ],
      },
    ],
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <LegalPage title="Terms of Service" lastUpdated="May 14, 2026">
      <p>
        Welcome to BrandForge. These Terms of Service (&quot;Terms&quot;) govern your use of our website
        and services at brandforge.ai and related subdomains (collectively, the &quot;Service&quot;).
        By accessing or using the Service, you agree to be bound by these Terms.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By creating an account or using the Service, you confirm that you are at least 13 years old
        and agree to these Terms. If you do not agree, please do not use the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        BrandForge provides an AI-powered business name generation tool and brand kit creation
        service. The Service allows you to:
      </p>
      <ul>
        <li>Describe your business idea and receive AI-generated name suggestions</li>
        <li>View name meanings, styles, and connotations</li>
        <li>Check domain and social media handle availability</li>
        <li>Generate comprehensive brand kits (logos, color palettes, taglines)</li>
        <li>Download and export brand kits</li>
      </ul>

      <h2>3. Free and Paid Tiers</h2>
      <p>
        <strong>Free Tier:</strong> You may use the basic name generation features at no cost, subject
        to usage limits. Free tier users receive a limited number of name generations per day.
      </p>
      <p>
        <strong>Pro Tier:</strong> Paid subscription解锁 unlimited name suggestions, brand kit generation,
        domain and social checks, and brand kit downloads. Pricing is displayed on our pricing page
        and may be updated from time to time.
      </p>

      <h2>4. Payment and Billing</h2>
      <ul>
        <li>
          Payments are processed securely through Stripe. We do not store your full credit card details.
        </li>
        <li>
          All prices are displayed in USD. You are responsible for any applicable taxes.
        </li>
        <li>
          We offer a 14-day money-back guarantee. If you are not satisfied, contact{' '}
          <a href="mailto:hello@brandforge.ai" className="text-brand-600 hover:text-brand-700 underline">
            hello@brandforge.ai
          </a>{' '}
          within 14 days of purchase for a full refund.
        </li>
        <li>
          Refund requests after 14 days are handled on a case-by-case basis.
        </li>
      </ul>

      <h2>5. Intellectual Property</h2>
      <h3>Your Content</h3>
      <p>
        You retain ownership of the business descriptions and ideas you submit to the Service.
        By submitting content, you grant us a limited license to process it for the purpose of
        generating names and brand kits for you.
      </p>
      <h3>Generated Names and Brand Kits</h3>
      <p>
        Names and brand materials generated by the Service are provided for your use. You are free
        to use generated names commercially. We make no guarantee that generated names are unique,
        untrademarked, or available — we recommend checking trademark databases and domain registrars
        in your jurisdiction before committing to a name.
      </p>
      <h3>BrandForge IP</h3>
      <p>
        The Service itself, including its design, code, algorithms, and user interface, is the
        intellectual property of BrandForge. You may not copy, modify, distribute, or reverse-engineer
        any part of the Service.
      </p>

      <h2>6. Acceptable Use</h2>
      <p>You agree <strong>not</strong> to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose</li>
        <li>Generate names that infringe on existing trademarks in bad faith</li>
        <li>Attempt to gain unauthorized access to our systems or other users&apos; accounts</li>
        <li>Use automated tools to scrape or excessively query the Service</li>
        <li>Interfere with or disrupt the Service&apos;s functionality</li>
        <li>Share your account credentials with others</li>
      </ul>

      <h2>7. User Accounts</h2>
      <p>
        You are responsible for maintaining the security of your account credentials. You must notify
        us immediately of any unauthorized use of your account. We are not liable for losses resulting
        from unauthorized access to your account.
      </p>

      <h2>8. Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, AND NON-INFRINGEMENT. WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED,
        ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, BRANDFORGE SHALL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES,
        WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER
        INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.
      </p>

      <h2>10. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless BrandForge and its officers, directors, employees,
        and agents from any claims, damages, losses, costs, or expenses (including reasonable
        attorneys&apos; fees) arising from your use of the Service or violation of these Terms.
      </p>

      <h2>11. Termination</h2>
      <p>
        We reserve the right to suspend or terminate your account at our sole discretion, without
        notice, for conduct that we believe violates these Terms or is harmful to other users,
        us, or third parties.
      </p>
      <p>
        You may terminate your account at any time by contacting us. Upon termination, your right
        to use the Service will immediately cease. Provisions that by their nature should survive
        termination will remain in effect.
      </p>

      <h2>12. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of material changes by
        posting the updated Terms on our website and updating the &quot;Last updated&quot; date.
        Your continued use of the Service after changes constitutes acceptance of the revised Terms.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the United States. Any disputes arising from these
        Terms or the Service shall be resolved in the courts of the applicable jurisdiction.
      </p>

      <h2>14. Contact</h2>
      <p>
        If you have questions about these Terms, please contact us at:{' '}
        <a href="mailto:hello@brandforge.ai" className="text-brand-600 hover:text-brand-700 underline">
          hello@brandforge.ai
        </a>
      </p>
    </LegalPage>
    </>
  )
}